import newsBg from '../../../public/newsBg.jpg'

const newsData = [
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
    {
        type: 'crypto',
        img: newsBg,
        title:'Bitcoin yeniden 20.000$’ın üzerine çıktı!',
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eu nibh posuere facilisi sed. Nullam placerat convallis elit molestie egestas massa.',
        source:'ShiftDelete.Net',
        publishDate:'03/10/2022',
    },
];


const news3Data = [
    {
        content:"Lorem ipsum dolor sit amet consectetur. Porttitor at aliquet feugiat ut sapien quis arcu et. Enim enim sit auctor ultrices turpis vitae cursus scelerisque. Elit massa velit cras tincidunt risus nisl diam. Accumsan nulla non integer adipiscing purus sed consectetur dignissim. Non tempus ante feugiat hendrerit elit mi interdum porta lacus. Odio elementum eu nec sit in quam pulvinar egestas et. Placerat venenatis nisi elementum vitae in turpis id. Lorem eget sagittis dictum interdum viverra est blandit dolor feugiat. Ut nec facilisis ipsum nunc nunc aliquam tellus. Mi enim scelerisque nisl dis interdum. In in aenean praesent ut morbi tortor lorem sagittis dui. Fringilla placerat ante proin ac est.Eget hendrerit suscipit at eget nec a facilisis massa facilisi. Volutpat urna ac augue nulla nulla augue arcu. Gravida massa lorem lectus nec ut dolor ullamcorper venenatis. Gravida iaculis tristique consectetur eget interdum vulputate. Cursus mi mollis sollicitudin ut eu libero mi feugiat. Donec lacus nec nullam arcu vel. Et suspendisse risus lorem nunc faucibus euismod quam pharetra. Dui ut quis scelerisque pellentesque turpis sit hendrerit morbi. Tellus amet adipiscing arcu amet est id amet ullamcorper. Massa tristique lorem odio fringilla fermentum.Integer elit dapibus ullamcorper nisl pulvinar sit faucibus. Pretium in est id massa urna gravida vitae a dolor. At nunc pellentesque maecenas magna. Auctor urna vitae tortor egestas metus morbi amet dolor. Orci ut gravida ullamcorper faucibus pellentesque. Id integer elementum varius a quis aenean sed leo hendrerit. Urna quis imperdiet nec et ac gravida sapien. Convallis ullamcorper et massa ut volutpat eget facilisis sit suspendisse. Sem vitae diam urna at quisque magnis. Eget interdum diam et cursus tortor placerat vulputate. Malesuada magna ut non malesuada quam vel viverra et. Porta maecenas urna arcu enim. Non habitant velit ipsum iaculis nunc maecenas. Amet tincidunt dictum lacus imperdiet tincidunt purus facilisis nec aliquam.",

    }
]
export  {newsData,news3Data}