import "./globals.css";
import Banner from "./components/banner";
import Header from "./components/header";
import Footer from "./components/footer";
import IosCard from "./components/iosCard";
import { UserProvider } from "./context/store.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <UserProvider>
          <Banner />
          <Header />

          {children}

          <IosCard />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
